In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

In [22]:
df=pd.read_excel("B2B_Transaction_Data_.xlsx")

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 664154 entries, 0 to 664153
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    664154 non-null  str
 1   CustomerID   664154 non-null  str
 2   InvoiceDate  664154 non-null  str
 3   StockCode    664154 non-null  int64
 4   Description  664154 non-null  object
 5   Category     664090 non-null  str
 6   City         657352 non-null  str
 7   Quantity     664148 non-null  float64
 8   NetPrice     664154 non-null  float64
 9   UnitPrice    664154 non-null  float64
dtypes: float64(3), int64(1), object(1), str(5)
memory usage: 50.7+ MB

In [24]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 664154 entries, 0 to 664153
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    664154 non-null  str
 1   CustomerID   664154 non-null  str
 2   InvoiceDate  664154 non-null  datetime64[us]
 3   StockCode    664154 non-null  int64
 4   Description  664154 non-null  object
 5   Category     664090 non-null  str
 6   City         657352 non-null  str
 7   Quantity     664148 non-null  float64
 8   NetPrice     664154 non-null  float64
 9   UnitPrice    664154 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(4)
memory usage: 50.7+ MB

In [27]:
df

,InvoiceNo,CustomerID,InvoiceDate,StockCode,Description,Category,City,Quantity,NetPrice,UnitPrice
0,BSR202000000027,A02348,2020-01-02,8698543133198,Anatolian Puzzle Dünya Siyasi Harita (3319),1000 Parça Puzzle,ISTANBUL,1.0,18.92,22.80
1,BSR202000000007,A02212,2020-01-02,8698543110793,Anatolian-Puzzle 1000 Kurt Timi,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30
2,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30
3,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30
4,BAD202000000028,A00905,2020-01-02,8698543110335,Gezegenler (Puzzle 1000) 1033,1000 Parça Puzzle,AYDIN,1.0,29.84,37.30
...,...,...,...,...,...,...,...,...,...,...
664149,BSR202000018601,A02218,2020-12-31,9786051980461,Mutfak Sırları,Yemek Kitapları,ISTANBUL,1.0,22.42,38.00
664150,BSR202000018601,A02218,2020-12-31,9786051734545,Şarap Tutkununun El Kitabı,Yemek Kitapları,ISTANBUL,1.0,17.99,29.50
664151,BAD202000029630,A00837,2020-12-31,9786052217498,Kafa Dengi TYT Challenger Matematik Soru Banka...,YKS (Yükseköğretim Kurumları Giriş Sınavı),TRABZON,2.0,25.85,47.00
664152,BSR202000018600,A01869,2020-12-31,9786058487475,Scrum - İki Katı İşi Yarı Zamanda Yapma Sanatı,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,29.99,49.98
664153,BAD202000029641,A01131,2020-12-31,9789753226455,Yöneticiler İçin Aristoteles,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,2.07,3.00

In [34]:
df["SalesRevenue"] = df["Quantity"] * df["NetPrice"]

In [35]:
df

,InvoiceNo,CustomerID,InvoiceDate,StockCode,Description,Category,City,Quantity,NetPrice,UnitPrice,SalesRevenue
0,BSR202000000027,A02348,2020-01-02,8698543133198,Anatolian Puzzle Dünya Siyasi Harita (3319),1000 Parça Puzzle,ISTANBUL,1.0,18.92,22.80,18.92
1,BSR202000000007,A02212,2020-01-02,8698543110793,Anatolian-Puzzle 1000 Kurt Timi,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84
2,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84
3,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84
4,BAD202000000028,A00905,2020-01-02,8698543110335,Gezegenler (Puzzle 1000) 1033,1000 Parça Puzzle,AYDIN,1.0,29.84,37.30,29.84
...,...,...,...,...,...,...,...,...,...,...,...
664149,BSR202000018601,A02218,2020-12-31,9786051980461,Mutfak Sırları,Yemek Kitapları,ISTANBUL,1.0,22.42,38.00,22.42
664150,BSR202000018601,A02218,2020-12-31,9786051734545,Şarap Tutkununun El Kitabı,Yemek Kitapları,ISTANBUL,1.0,17.99,29.50,17.99
664151,BAD202000029630,A00837,2020-12-31,9786052217498,Kafa Dengi TYT Challenger Matematik Soru Banka...,YKS (Yükseköğretim Kurumları Giriş Sınavı),TRABZON,2.0,25.85,47.00,51.70
664152,BSR202000018600,A01869,2020-12-31,9786058487475,Scrum - İki Katı İşi Yarı Zamanda Yapma Sanatı,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,29.99,49.98,29.99
664153,BAD202000029641,A01131,2020-12-31,9789753226455,Yöneticiler İçin Aristoteles,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,2.07,3.00,2.07

In [36]:
df["month"] = pd.DatetimeIndex(df["InvoiceDate"]).month

In [37]:
df

,InvoiceNo,CustomerID,InvoiceDate,StockCode,Description,Category,City,Quantity,NetPrice,UnitPrice,SalesRevenue,month
0,BSR202000000027,A02348,2020-01-02,8698543133198,Anatolian Puzzle Dünya Siyasi Harita (3319),1000 Parça Puzzle,ISTANBUL,1.0,18.92,22.80,18.92,1
1,BSR202000000007,A02212,2020-01-02,8698543110793,Anatolian-Puzzle 1000 Kurt Timi,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84,1
2,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84,1
3,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.30,29.84,1
4,BAD202000000028,A00905,2020-01-02,8698543110335,Gezegenler (Puzzle 1000) 1033,1000 Parça Puzzle,AYDIN,1.0,29.84,37.30,29.84,1
...,...,...,...,...,...,...,...,...,...,...,...,...
664149,BSR202000018601,A02218,2020-12-31,9786051980461,Mutfak Sırları,Yemek Kitapları,ISTANBUL,1.0,22.42,38.00,22.42,12
664150,BSR202000018601,A02218,2020-12-31,9786051734545,Şarap Tutkununun El Kitabı,Yemek Kitapları,ISTANBUL,1.0,17.99,29.50,17.99,12
664151,BAD202000029630,A00837,2020-12-31,9786052217498,Kafa Dengi TYT Challenger Matematik Soru Banka...,YKS (Yükseköğretim Kurumları Giriş Sınavı),TRABZON,2.0,25.85,47.00,51.70,12
664152,BSR202000018600,A01869,2020-12-31,9786058487475,Scrum - İki Katı İşi Yarı Zamanda Yapma Sanatı,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,29.99,49.98,29.99,12
664153,BAD202000029641,A01131,2020-12-31,9789753226455,Yöneticiler İçin Aristoteles,Yönetim / İş Geliştirme / Kalite,ISTANBUL,1.0,2.07,3.00,2.07,12

In [42]:
df_2=df.groupby(["StockCode","month"])["SalesRevenue"].sum().to_frame().reset_index()

In [43]:
df_2

            StockCode  month  SalesRevenue
0       2014031812295      1         19.25
1       2014031812295      2         78.05
2       2014031812295      3         57.75
3       2014051515350      1         38.50
4       2014051515350      2        115.50
...               ...    ...           ...
185438  9915779139213      9         45.50
185439  9915779139213     10         63.00
185440  9915779139213     12        112.50
185441  9915795156355      4         19.05
185442  9915795156355     10         24.13

[185443 rows x 3 columns]

In [48]:
df_3=df_2.pivot(index="StockCode",columns="month",values="SalesRevenue").fillna(0).reset_index()

In [49]:
df_3

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,0.00,0.00,34.05,34.05,0.00,0.00,0.0,0.0,0.0,86.26,0.0,0.00
43574,9915779133884,0.00,0.00,33.00,0.00,33.00,0.00,54.0,0.0,0.0,68.60,42.0,157.50
43575,9915779135482,0.00,0.00,16.50,0.00,33.00,0.00,0.0,0.0,0.0,40.80,0.0,100.50
43576,9915779139213,0.00,0.00,15.00,21.00,24.00,0.00,0.0,0.0,45.5,63.00,0.0,112.50
43577,9915795156355,0.00,0.00,0.00,19.05,0.00,0.00,0.0,0.0,0.0,24.13,0.0,0.00

In [52]:
df_3["total_sales"]= df_3.iloc[:,1:13].sum(axis=1, numeric_only=True) #axis sıfır olunca sütun bazlı topluyor satır satır işlem yapmak demek axis = 1 demek.

In [53]:
df_3

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12,total_sales
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,155.05
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25,500.50
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,84.37
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00,329.30
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00,277.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,0.00,0.00,34.05,34.05,0.00,0.00,0.0,0.0,0.0,86.26,0.0,0.00,154.36
43574,9915779133884,0.00,0.00,33.00,0.00,33.00,0.00,54.0,0.0,0.0,68.60,42.0,157.50,388.10
43575,9915779135482,0.00,0.00,16.50,0.00,33.00,0.00,0.0,0.0,0.0,40.80,0.0,100.50,190.80
43576,9915779139213,0.00,0.00,15.00,21.00,24.00,0.00,0.0,0.0,45.5,63.00,0.0,112.50,281.00
43577,9915795156355,0.00,0.00,0.00,19.05,0.00,0.00,0.0,0.0,0.0,24.13,0.0,0.00,43.18

In [57]:
df_3["Average_sales"]= df_3["total_sales"]/12
df_3["std_dev"]=df_3.iloc[:,1:13].std(axis=1, numeric_only=True)

In [58]:
df_3

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12,total_sales,Average_sales,std_dev
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,155.05,12.920833,26.618606
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25,500.50,41.708333,37.465262
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,84.37,7.030833,24.355521
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00,329.30,27.441667,19.652999
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00,277.75,23.145833,23.841936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,0.00,0.00,34.05,34.05,0.00,0.00,0.0,0.0,0.0,86.26,0.0,0.00,154.36,12.863333,26.584357
43574,9915779133884,0.00,0.00,33.00,0.00,33.00,0.00,54.0,0.0,0.0,68.60,42.0,157.50,388.10,32.341667,46.532891
43575,9915779135482,0.00,0.00,16.50,0.00,33.00,0.00,0.0,0.0,0.0,40.80,0.0,100.50,190.80,15.900000,30.290142
43576,9915779139213,0.00,0.00,15.00,21.00,24.00,0.00,0.0,0.0,45.5,63.00,0.0,112.50,281.00,23.416667,34.846960
43577,9915795156355,0.00,0.00,0.00,19.05,0.00,0.00,0.0,0.0,0.0,24.13,0.0,0.00,43.18,3.598333,8.473399

In [59]:
df_3["CV"] = df_3["std_dev"]/df_3["Average_sales"]

In [60]:
df_3

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12,total_sales,Average_sales,std_dev,CV
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,155.05,12.920833,26.618606,2.060131
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25,500.50,41.708333,37.465262,0.898268
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,84.37,7.030833,24.355521,3.464102
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00,329.30,27.441667,19.652999,0.716174
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00,277.75,23.145833,23.841936,1.030075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,0.00,0.00,34.05,34.05,0.00,0.00,0.0,0.0,0.0,86.26,0.0,0.00,154.36,12.863333,26.584357,2.066677
43574,9915779133884,0.00,0.00,33.00,0.00,33.00,0.00,54.0,0.0,0.0,68.60,42.0,157.50,388.10,32.341667,46.532891,1.438791
43575,9915779135482,0.00,0.00,16.50,0.00,33.00,0.00,0.0,0.0,0.0,40.80,0.0,100.50,190.80,15.900000,30.290142,1.905040
43576,9915779139213,0.00,0.00,15.00,21.00,24.00,0.00,0.0,0.0,45.5,63.00,0.0,112.50,281.00,23.416667,34.846960,1.488126
43577,9915795156355,0.00,0.00,0.00,19.05,0.00,0.00,0.0,0.0,0.0,24.13,0.0,0.00,43.18,3.598333,8.473399,2.354812

In [62]:
def xyz_analysis(x):
    if x<=0.5:
        return "X"
    elif x>0.5 and x<=1:
        return "Y"
    else:
        return "Z"

In [64]:
df_3["XYZ_Class"]= df_3["CV"].apply(xyz_analysis)

In [66]:
df_3

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12,total_sales,Average_sales,std_dev,CV,XYZ_Class
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,155.05,12.920833,26.618606,2.060131,Z
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25,500.50,41.708333,37.465262,0.898268,Y
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,84.37,7.030833,24.355521,3.464102,Z
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00,329.30,27.441667,19.652999,0.716174,Y
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00,277.75,23.145833,23.841936,1.030075,Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,0.00,0.00,34.05,34.05,0.00,0.00,0.0,0.0,0.0,86.26,0.0,0.00,154.36,12.863333,26.584357,2.066677,Z
43574,9915779133884,0.00,0.00,33.00,0.00,33.00,0.00,54.0,0.0,0.0,68.60,42.0,157.50,388.10,32.341667,46.532891,1.438791,Z
43575,9915779135482,0.00,0.00,16.50,0.00,33.00,0.00,0.0,0.0,0.0,40.80,0.0,100.50,190.80,15.900000,30.290142,1.905040,Z
43576,9915779139213,0.00,0.00,15.00,21.00,24.00,0.00,0.0,0.0,45.5,63.00,0.0,112.50,281.00,23.416667,34.846960,1.488126,Z
43577,9915795156355,0.00,0.00,0.00,19.05,0.00,0.00,0.0,0.0,0.0,24.13,0.0,0.00,43.18,3.598333,8.473399,2.354812,Z

In [69]:
df_4=df_3.groupby("StockCode").agg(total_revenue=("total_sales","sum")).sort_values(by="total_revenue",ascending=False).reset_index()

In [70]:
df_4

           StockCode  total_revenue
0      9786058213241  478576.548226
1      9786058422841  201214.900000
2      9786056883569  182617.760000
3      9789754054453  165152.409998
4      9789752430990  149732.088950
...              ...            ...
43573  9786051145228       1.580000
43574  9786052944851       1.350000
43575  9786056969560       0.004063
43576  9786052950319       0.000000
43577  9789751419149       0.000000

[43578 rows x 2 columns]

In [71]:
df_4["cumulative"]=df_4["total_revenue"].cumsum()

In [72]:
df_4

           StockCode  total_revenue    cumulative
0      9786058213241  478576.548226  4.785765e+05
1      9786058422841  201214.900000  6.797914e+05
2      9786056883569  182617.760000  8.624092e+05
3      9789754054453  165152.409998  1.027562e+06
4      9789752430990  149732.088950  1.177294e+06
...              ...            ...           ...
43573  9786051145228       1.580000  2.957996e+07
43574  9786052944851       1.350000  2.957996e+07
43575  9786056969560       0.004063  2.957996e+07
43576  9786052950319       0.000000  2.957996e+07
43577  9789751419149       0.000000  2.957996e+07

[43578 rows x 3 columns]

In [75]:
df_4["total_cumulative"]=df_4["total_revenue"].sum()
df_4["sku_percent"]=df_4["cumulative"]/df_4["total_cumulative"]

In [76]:
df_4

,StockCode,total_revenue,cumulative,total_cumulative,sku_percent
0,9786058213241,478576.548226,4.785765e+05,2.957996e+07,0.016179
1,9786058422841,201214.900000,6.797914e+05,2.957996e+07,0.022981
2,9786056883569,182617.760000,8.624092e+05,2.957996e+07,0.029155
3,9789754054453,165152.409998,1.027562e+06,2.957996e+07,0.034738
4,9789752430990,149732.088950,1.177294e+06,2.957996e+07,0.039800
...,...,...,...,...,...
43573,9786051145228,1.580000,2.957996e+07,2.957996e+07,1.000000
43574,9786052944851,1.350000,2.957996e+07,2.957996e+07,1.000000
43575,9786056969560,0.004063,2.957996e+07,2.957996e+07,1.000000
43576,9786052950319,0.000000,2.957996e+07,2.957996e+07,1.000000
43577,9789751419149,0.000000,2.957996e+07,2.957996e+07,1.000000

In [77]:
def abc_classfication(x):
    if x>0 and x<=0.8:
        return "A"
    elif x>0.8 and x<=0.95:
        return "B"
    else:
        return "C"

df_4["ABC_Class"]= df_4["sku_percent"].apply(abc_classfication)

In [78]:
df_4

,StockCode,total_revenue,cumulative,total_cumulative,sku_percent,ABC_Class
0,9786058213241,478576.548226,4.785765e+05,2.957996e+07,0.016179,A
1,9786058422841,201214.900000,6.797914e+05,2.957996e+07,0.022981,A
2,9786056883569,182617.760000,8.624092e+05,2.957996e+07,0.029155,A
3,9789754054453,165152.409998,1.027562e+06,2.957996e+07,0.034738,A
4,9789752430990,149732.088950,1.177294e+06,2.957996e+07,0.039800,A
...,...,...,...,...,...,...
43573,9786051145228,1.580000,2.957996e+07,2.957996e+07,1.000000,C
43574,9786052944851,1.350000,2.957996e+07,2.957996e+07,1.000000,C
43575,9786056969560,0.004063,2.957996e+07,2.957996e+07,1.000000,C
43576,9786052950319,0.000000,2.957996e+07,2.957996e+07,1.000000,C
43577,9789751419149,0.000000,2.957996e+07,2.957996e+07,1.000000,C

In [79]:
df_3.head()

month,StockCode,1,2,3,4,5,6,7,8,9,10,11,12,total_sales,Average_sales,std_dev,CV,XYZ_Class
0,2014031812295,19.25,78.05,57.75,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,155.05,12.920833,26.618606,2.060131,Z
1,2014051515350,38.50,115.50,57.75,57.75,19.25,19.25,38.5,0.0,0.0,57.75,0.0,96.25,500.50,41.708333,37.465262,0.898268,Y
2,2015051412335,0.00,84.37,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,84.37,7.030833,24.355521,3.464102,Z
3,2016000014501,13.00,26.00,16.25,68.25,39.00,39.00,0.0,35.1,23.4,22.50,46.8,0.00,329.30,27.441667,19.652999,0.716174,Y
4,2016000014532,0.00,15.60,14.95,68.25,68.25,29.25,0.0,11.7,23.4,11.25,35.1,0.00,277.75,23.145833,23.841936,1.030075,Z

In [81]:
df_3_=df_3[["StockCode","total_sales","Average_sales","std_dev","CV","XYZ_Class"]]
df_4_=df_4[["StockCode","total_revenue","sku_percent","ABC_Class"]]
df_final=pd.merge(df_3_,df_4_,on="StockCode",how="left")

In [82]:
df_final

,StockCode,total_sales,Average_sales,std_dev,CV,XYZ_Class,total_revenue,sku_percent,ABC_Class
0,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B
1,2014051515350,500.50,41.708333,37.465262,0.898268,Y,500.50,0.879571,B
2,2015051412335,84.37,7.030833,24.355521,3.464102,Z,84.37,0.971951,C
3,2016000014501,329.30,27.441667,19.652999,0.716174,Y,329.30,0.906680,B
4,2016000014532,277.75,23.145833,23.841936,1.030075,Z,277.75,0.916952,B
...,...,...,...,...,...,...,...,...,...
43573,9915777755927,154.36,12.863333,26.584357,2.066677,Z,154.36,0.948635,B
43574,9915779133884,388.10,32.341667,46.532891,1.438791,Z,388.10,0.896521,B
43575,9915779135482,190.80,15.900000,30.290142,1.905040,Z,190.80,0.938437,B
43576,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B
43577,9915795156355,43.18,3.598333,8.473399,2.354812,Z,43.18,0.988180,C

In [88]:
df_final["stock_class"]=df_final["ABC_Class"]+df_final["XYZ_Class"]

In [89]:
df_final

,StockCode,total_sales,Average_sales,std_dev,CV,XYZ_Class,total_revenue,sku_percent,ABC_Class,stock_class
0,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ
1,2014051515350,500.50,41.708333,37.465262,0.898268,Y,500.50,0.879571,B,BY
2,2015051412335,84.37,7.030833,24.355521,3.464102,Z,84.37,0.971951,C,CZ
3,2016000014501,329.30,27.441667,19.652999,0.716174,Y,329.30,0.906680,B,BY
4,2016000014532,277.75,23.145833,23.841936,1.030075,Z,277.75,0.916952,B,BZ
...,...,...,...,...,...,...,...,...,...,...
43573,9915777755927,154.36,12.863333,26.584357,2.066677,Z,154.36,0.948635,B,BZ
43574,9915779133884,388.10,32.341667,46.532891,1.438791,Z,388.10,0.896521,B,BZ
43575,9915779135482,190.80,15.900000,30.290142,1.905040,Z,190.80,0.938437,B,BZ
43576,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B,BZ
43577,9915795156355,43.18,3.598333,8.473399,2.354812,Z,43.18,0.988180,C,CZ

In [90]:
df.head(

)

,InvoiceNo,CustomerID,InvoiceDate,StockCode,Description,Category,City,Quantity,NetPrice,UnitPrice,SalesRevenue,month
0,BSR202000000027,A02348,2020-01-02,8698543133198,Anatolian Puzzle Dünya Siyasi Harita (3319),1000 Parça Puzzle,ISTANBUL,1.0,18.92,22.8,18.92,1
1,BSR202000000007,A02212,2020-01-02,8698543110793,Anatolian-Puzzle 1000 Kurt Timi,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.3,29.84,1
2,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.3,29.84,1
3,BSR202000000019,A02212,2020-01-02,8698543110779,Anatolian-Puzzle 1000 Mustafa Kemal Atatürk,1000 Parça Puzzle,ISTANBUL,1.0,29.84,37.3,29.84,1
4,BAD202000000028,A00905,2020-01-02,8698543110335,Gezegenler (Puzzle 1000) 1033,1000 Parça Puzzle,AYDIN,1.0,29.84,37.3,29.84,1

In [96]:
df_selected_columns=df[["StockCode","Description"]]
df_merge=pd.merge(df_final,df_selected_columns,on="StockCode",how="left")

In [97]:
df_merge

,StockCode,total_sales,Average_sales,std_dev,CV,XYZ_Class,total_revenue,sku_percent,ABC_Class,stock_class,Description
0,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
1,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
2,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
3,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
4,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
...,...,...,...,...,...,...,...,...,...,...,...
664149,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B,BZ,Ömer Seyfettin Hikayeleri Seti 10 Kitap
664150,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B,BZ,Ömer Seyfettin Hikayeleri Seti 10 Kitap
664151,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B,BZ,Ömer Seyfettin Hikayeleri Seti 10 Kitap
664152,9915795156355,43.18,3.598333,8.473399,2.354812,Z,43.18,0.988180,C,CZ,Sabahattin Ali Kitaplığı
664153,9915795156355,43.18,3.598333,8.473399,2.354812,Z,43.18,0.988180,C,CZ,Sabahattin Ali Kitaplığı

In [100]:
df_result=df_merge.drop_duplicates()

In [101]:
df_result

,StockCode,total_sales,Average_sales,std_dev,CV,XYZ_Class,total_revenue,sku_percent,ABC_Class,stock_class,Description
0,2014031812295,155.05,12.920833,26.618606,2.060131,Z,155.05,0.948415,B,BZ,Arapça 5. Sınıf Hikaye Seti
5,2014051515350,500.50,41.708333,37.465262,0.898268,Y,500.50,0.879571,B,BY,Hikayelerle Arapça Öğreniyorum Serisi
23,2015051412335,84.37,7.030833,24.355521,3.464102,Z,84.37,0.971951,C,CZ,Evvel Zaman İçinde 15 Kitap
24,2016000014501,329.30,27.441667,19.652999,0.716174,Y,329.30,0.906680,B,BY,Buzzi Zeka Oyunları 1
53,2016000014532,277.75,23.145833,23.841936,1.030075,Z,277.75,0.916952,B,BZ,Buzzi Zeka Oyunları 4
...,...,...,...,...,...,...,...,...,...,...,...
664122,9915777755927,154.36,12.863333,26.584357,2.066677,Z,154.36,0.948635,B,BZ,Sabahattin Ali Kitaplığı Seti 10 Kitap
664125,9915779133884,388.10,32.341667,46.532891,1.438791,Z,388.10,0.896521,B,BZ,Jules Verne Serisi 10 Kitap
664135,9915779135482,190.80,15.900000,30.290142,1.905040,Z,190.80,0.938437,B,BZ,Franz Kafka 10 Kitap (Kutulu Set)
664142,9915779139213,281.00,23.416667,34.846960,1.488126,Z,281.00,0.916385,B,BZ,Ömer Seyfettin Hikayeleri Seti 10 Kitap
664152,9915795156355,43.18,3.598333,8.473399,2.354812,Z,43.18,0.988180,C,CZ,Sabahattin Ali Kitaplığı

In [102]:
filtered_df=df_result[df_result["stock_class"]=="AX"]

In [103]:
filtered_df

,StockCode,total_sales,Average_sales,std_dev,CV,XYZ_Class,total_revenue,sku_percent,ABC_Class,stock_class,Description
12343,9786050812947,1624.620000,135.385000,59.475438,0.439306,X,1624.620000,0.767029,A,AX,Osmanlı Tarihi Kayı 2 - Cihan Devleti
13365,9786050817676,3781.250000,315.104167,120.273323,0.381694,X,3781.250000,0.649207,A,AX,Levent Türkiye'yi Geziyorum - 03 Set (5 Kitap ...
23231,9786050831597,9678.750000,806.562500,299.904438,0.371830,X,9678.750000,0.495255,A,AX,Karışık - Ciltsiz
26002,9786050922639,1718.060000,143.171667,63.581419,0.444092,X,1718.060000,0.760605,A,AX,Pembe ve Yusuf
26564,9786050926316,7633.100000,636.091667,243.321164,0.382525,X,7633.100000,0.532374,A,AX,Konstantiniyye Oteli
...,...,...,...,...,...,...,...,...,...,...,...
642832,9789944696647,2847.988848,237.332404,87.548806,0.368887,X,2847.988848,0.693343,A,AX,Süper Gazeteciler-4 (Belalı Davetiye)
643044,9789944697682,2674.000000,222.833333,104.281327,0.467979,X,2674.000000,0.702680,A,AX,Gülen Sakız Ağacı
657141,9789944884518,3847.610000,320.634167,122.052756,0.380660,X,3847.610000,0.646625,A,AX,Othello - Hasan Ali Yücel Klasikleri
660133,9789944888349,9904.140000,825.345000,340.849796,0.412979,X,9904.140000,0.489300,A,AX,Nutuk-Gençler İçin Fotoğraflarla
661231,9789944889858,4032.380000,336.031667,166.606432,0.495806,X,4032.380000,0.639019,A,AX,Ölü Canlar - Hasan Ali Yücel Klasikleri

In [104]:
df_result["stock_class"].value_counts()

stock_class
CZ    28952
BZ     7960
BY     2784
AY     1698
AZ     1529
CY      425
AX      170
BX       58
CX        2
Name: count, dtype: int64

In [105]:
df_result.to_excel("InventoryClassification.xlsx",index=False)